#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Deze code is gegenereerd met een hulpprogramma.
//     Runtime-versie:4.0.30319.34014
//
//     Als u wijzigingen aanbrengt in dit bestand, kan dit onjuist gedrag veroorzaken wanneer
//     de code wordt gegenereerd.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("RoboRally.Resource", IsApplication=true)]

namespace RoboRally
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int addplayer_icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Backup_Active = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Backup_Inactive = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int game_icon = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int game_icon_small = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int gameboard = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int grunge = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int grunge_noscale = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int icon = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int life_bar = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int loading = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int Move3_Active = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int Move3_Inactive = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int RotateRight_Active = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int RotateRight_Inactive = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int rr_logo = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int settings_icon = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int user_icon = 2130837521;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070027
			public const int aanmeldBericht = 2131165223;
			
			// aapt resource value: 0x7f07002b
			public const int accountButton = 2131165227;
			
			// aapt resource value: 0x7f070018
			public const int amountDisplay = 2131165208;
			
			// aapt resource value: 0x7f07002e
			public const int backButton = 2131165230;
			
			// aapt resource value: 0x7f070002
			public const int controlButton1 = 2131165186;
			
			// aapt resource value: 0x7f070003
			public const int controlButton2 = 2131165187;
			
			// aapt resource value: 0x7f070004
			public const int controlButton3 = 2131165188;
			
			// aapt resource value: 0x7f070005
			public const int controlButton4 = 2131165189;
			
			// aapt resource value: 0x7f070006
			public const int controlButton5 = 2131165190;
			
			// aapt resource value: 0x7f07000e
			public const int errorHandler = 2131165198;
			
			// aapt resource value: 0x7f070007
			public const int finishGame = 2131165191;
			
			// aapt resource value: 0x7f070028
			public const int firstName = 2131165224;
			
			// aapt resource value: 0x7f070001
			public const int gameBoard = 2131165185;
			
			// aapt resource value: 0x7f070016
			public const int infoText = 2131165206;
			
			// aapt resource value: 0x7f070013
			public const int instellingenButton = 2131165203;
			
			// aapt resource value: 0x7f070029
			public const int lastName = 2131165225;
			
			// aapt resource value: 0x7f07001a
			public const int leaveButton = 2131165210;
			
			// aapt resource value: 0x7f070000
			public const int lifeBar = 2131165184;
			
			// aapt resource value: 0x7f070014
			public const int lobbyIcon = 2131165204;
			
			// aapt resource value: 0x7f070010
			public const int loggedName = 2131165200;
			
			// aapt resource value: 0x7f070009
			public const int loginBericht = 2131165193;
			
			// aapt resource value: 0x7f07000c
			public const int loginButton = 2131165196;
			
			// aapt resource value: 0x7f070008
			public const int mainLogo = 2131165192;
			
			// aapt resource value: 0x7f070012
			public const int multiplayerButton = 2131165202;
			
			// aapt resource value: 0x7f070015
			public const int pageHeaderName = 2131165205;
			
			// aapt resource value: 0x7f07001b
			public const int playerIcon1 = 2131165211;
			
			// aapt resource value: 0x7f07001d
			public const int playerIcon2 = 2131165213;
			
			// aapt resource value: 0x7f07001f
			public const int playerIcon3 = 2131165215;
			
			// aapt resource value: 0x7f070021
			public const int playerIcon4 = 2131165217;
			
			// aapt resource value: 0x7f070023
			public const int playerIcon5 = 2131165219;
			
			// aapt resource value: 0x7f070025
			public const int playerIcon6 = 2131165221;
			
			// aapt resource value: 0x7f07001c
			public const int playerName1 = 2131165212;
			
			// aapt resource value: 0x7f07001e
			public const int playerName2 = 2131165214;
			
			// aapt resource value: 0x7f070020
			public const int playerName3 = 2131165216;
			
			// aapt resource value: 0x7f070022
			public const int playerName4 = 2131165218;
			
			// aapt resource value: 0x7f070024
			public const int playerName5 = 2131165220;
			
			// aapt resource value: 0x7f070026
			public const int playerName6 = 2131165222;
			
			// aapt resource value: 0x7f07000d
			public const int registerButton = 2131165197;
			
			// aapt resource value: 0x7f07002c
			public const int settingsIcon = 2131165228;
			
			// aapt resource value: 0x7f070011
			public const int singleplayerButton = 2131165201;
			
			// aapt resource value: 0x7f070017
			public const int sliderBar = 2131165207;
			
			// aapt resource value: 0x7f070019
			public const int startGameButton = 2131165209;
			
			// aapt resource value: 0x7f07002d
			public const int toggleMusicButton = 2131165229;
			
			// aapt resource value: 0x7f07000f
			public const int userIcon = 2131165199;
			
			// aapt resource value: 0x7f07000a
			public const int userName = 2131165194;
			
			// aapt resource value: 0x7f07000b
			public const int userPass = 2131165195;
			
			// aapt resource value: 0x7f07002a
			public const int userPassVerify = 2131165226;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Game = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Login = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Menu = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int OfflineLobby = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int OnlineLobby = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Register = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int Setting = 2130903046;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7f040000
			public const int Sneak = 2130968576;
			
			static Raw()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Raw()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int Hello = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int Theme_Splash = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
